services:
  web-api:
    image: purylte/lat-api:latest
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development  
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db

  db:
    image: purylte/lat-db:latest
    build: 
      context: .
      dockerfile: Dockerfile.mysql
    ports:
      - 3307:3306